services:
  site-server:
    build: .
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - ./sws.config.toml:/config.toml
    environment:
      - SERVER_CONFIG_FILE=/config.toml

networks:
  traefik-proxy:
    external: true
